### ISSUE TITLE
Brak kanału nicktoons

### ISSUE THREAD

**Issue by notoco** [MajkiIT/kodi#1]
W epg brakuje programu Nicktoons
https://programtv.onet.pl/program-tv/nickelodeon-hd-44
http://m.interia.pl/program-tv/teraz/nicktoons-hd,cid,94591845,o,-1

BTW - świetna robota :) Idealnie pasuje do mojej ulubionej listy.

**Comment by MajkiIT** [comment]
jest 
```
  <programme start="20190212000000 +0100" stop="20190212002000 +0100" channel="Nicktoons">
    <title lang="pl">Świń, Koza, Banan, Robal : Jimmy Ron Robal. Pig Goat Banana Cricket 2, s02e07</title>
    <desc lang="pl">Perypetie czwórki przyjaciół: naiwnej świni, kozy artystki, samolubnego banana i zwariowanego naukowca świerszcza. Każdego dnia przeżywają oni wiele absurdalnych i zabawnych przygód.</desc>
    <date>2015</date>
    <category lang="pl">Serial</category>
    <category lang="pl">Animowany</category>
    <icon src="http://ocdn.eu/images/program-tv/ODc7MDA_/1ec800e3b64abf264a28b272eb155ab6.jpg" />
    <episode-num system="onscreen">2, odc. 7</episode-num>
    <episode-num system="onscreen">S2 E7</episode-num>
    <rating>
      <value>7</value>
    </rating>
  </programme>
```

**Comment by notoco** [comment]
Jest w epg 6, 11, 1, 5, 2, 3. W 7 (a na niej najlepiej mi działa kodi) i pozostałych nie ma...
Jakie są różnice pomiędzy poszczególnymi EPG - na jaki okres są przygotowywane, kiedy aktualizowane...

**Comment by MajkiIT** [comment]
Program buduje w zależności od źródła na 24h - 48 h. Pliki wrzucam na Githuba co 8 h.

**Comment by notoco** [comment]
Ok. Przywykłem że za pomocą crona ściągam sobie listę na boxa i ewentualnie za pomocą sed nanoszę poprawki z automatu. Z listą nr 7 nie muszę nic robić, jest idealna, ale nawyk został. Odpalę u siebie crona też co 8h.

**Comment by MajkiIT** [comment]
Ok, jak widać, najczęściej są 2 zmiany dziennie https://github.com/MajkiIT/kodi/commits/master/EPG/epg_v7.xml

**Comment by notoco** [comment]
A coś z tym nicktoons da się "ogarnąć" na tej liście?

**Comment by notoco** [comment]
Ok - v 14 ma w sobie też wszystko, jest na wiele dni, wymagała kilku poprawek ale ogólnie jest niezła

**Comment by MajkiIT** [comment]
@notoco 13 i 14 to wersja testowa. Trochę robię ją na około i innym narzędziem. Po zbadaniu wszystkich możliwości będę wiedział co jest najlepsze.

**Comment by notoco** [comment]
ej - ale nie zabieraj mi 7 ;)
