### ISSUE TITLE
PL iptv 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/kodi#4]
@MajkiIT / @notoco podajcie jakies dobre iptv z PL kanalami w HD please?

**Comment by MajkiIT** [comment]
Chodzi Ci o płatne czy free ?

**Comment by xxcriticxx** [comment]
@MajkiIT platne

**Comment by MajkiIT** [comment]
@xxcriticxx może http://bestbuyiptv.net/ ?

**Comment by xxcriticxx** [comment]
@MajkiIT ile kanalow PL? w jakiej jakosci?

**Comment by notoco** [comment]
@xxcriticxx - już ci kiedyś mówiłem - oficjalnie nie używam.

**Comment by MajkiIT** [comment]
@xxcriticxx 176 bez VOD. U nich masz wszystkie kanały ze świata, 720/1080p z przewagą 1080p

**Comment by xxcriticxx** [comment]
@MajkiIT da rade to jakos nagrywac?

**Comment by MajkiIT** [comment]
Nie próbowałem, ale w KODI jest taka możliwość https://forum.kodi.tv/showthread.php?tid=326896 lub z kompa przez VLC
