### ISSUE TITLE
router

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/kodi#5]
@MajkiIT orginalnie mam Conel XR5i v2 i musze go wymienic. jaki mikrotik router posiada dual wan?

**Comment by MajkiIT** [comment]
A jakie masz łącza internetowe ?

**Comment by xxcriticxx** [comment]
@majkit posiadam cable i fiber ale szukam routera co zrobi roll over jak jeden internet padnie

**Comment by MajkiIT** [comment]
@xxcriticxx chodzi mi jakie masz prędkości internetu aby router mógł to obsłużyć.

**Comment by xxcriticxx** [comment]
@MajkiIT gb router wystarczy
